export const DEFAULT_NOTIFICATION_RETENTION_DAYS = 90;
export const DEFAULT_AUDIT_RETENTION_DAYS = 180;
export const DEFAULT_JOBS_RETENTION_DAYS = 30;
export const RESET_REQUIRED_FACILITY_HASH = "$2b$10$zIN5eU5a4P.45wgaiqCJzuw2vPDgNdYT1Lmr6eeHxndRxzS3rLsb6";
