-- Migration neutralized.
-- The remote database schema was already synced via db push, causing conflicts with this migration.
-- This empty migration ensures Prisma marks it as applied without throwing "already exists" errors.
